# che-data-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: che-data-volume
  labels:
    type: local
spec:
  storageClassName: che-data-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/vagrant/che-data-storage"
  claimRef:
    namespace: che
    name: che-data-volume
