# uses dind for docker daemon with kubedm inside dind
Vagrant.configure("2") do |config|
    ENV['http_proxy']  = 'http://{proxyhost}:{proxyport}'
    ENV['https_proxy'] = 'http://{proxyhost}:{proxyport}'
    ENV['no_proxy'] = 'localhost,127.0.0.1'
    ENV['docker_version'] = '1.19.2'
    # Plugin installation procedure from http://stackoverflow.com/a/28801317
    config.vm.synced_folder '.' '/tmp/vagrant'

    required_plugins = %w(vagrant-proxyconf)
    puts "configuring docker and dns cloud proxies"
    if Vagrant.has_plugin?("vagrant-proxyconf")
        puts "find proxyconf plugin !"
        if ENV["http_proxy"]
          puts "http_proxy: " + ENV["http_proxy"]
          config.proxy.http  = ENV["http_proxy"]
        end
        if ENV["https_proxy"]
          puts "https_proxy: " + ENV["https_proxy"]
          config.proxy.https    = ENV["https_proxy"]
        end
        if ENV["no_proxy"]
          config.proxy.no_proxy = ENV["no_proxy"]
        end
    end    
    config.vm.provider "docker" do |d|
        d.build_dir '.' 
    end
end